export const COMMON_FIELDS = {
  type: { type: 'enum', required: true },
  status: { type: 'enum', values: ['stub', 'draft', 'active', 'archived'] },
  created: { type: 'date' },
  updated: { type: 'date' },
  aliases: { type: 'string[]' },
  tags: { type: 'string[]' },
};

export const ENTITIES = {
  regiao: { folder: 'regioes', required: ['type'],
    relations: { parent_region: { target: 'regiao' } } },
  local: { folder: 'locais', required: ['type', 'region'],
    relations: { region: { target: 'regiao' }, faction_control: { target: 'faccao' } } },
  npc: { folder: 'npcs', required: ['type', 'role'],
    fields: { role: { type: 'enum', values: ['ally', 'neutral', 'antagonist', 'patron'], required: true } },
    relations: { location: { target: 'local' }, faction: { target: 'faccao' }, statblock: { target: 'inimigo' } } },
  jogador: { folder: 'jogadores', required: ['type', 'player'],
    relations: { faction: { target: 'faccao' }, location: { target: 'local' },
      region: { target: 'regiao' } } },
  inimigo: { folder: 'inimigos', required: ['type'], relations: {} },
  faccao: { folder: 'faccoes', required: ['type'],
    relations: { key_members: { target: 'npc', many: true, curated: true },
      headquarters: { target: 'local' }, rivals: { target: 'faccao', many: true } } },
  quest: { folder: 'quests', required: ['type', 'act', 'status'],
    fields: { status: { type: 'enum', values: ['available', 'active', 'completed', 'failed', 'abandoned'], required: true } },
    relations: { act: { target: 'ato' }, giver: { target: 'npc' }, npcs: { target: 'npc', many: true },
      locations: { target: 'local', many: true }, items: { target: 'item', many: true },
      factions: { target: 'faccao', many: true } } },
  sessao: { folder: 'sessoes', required: ['type', 'date'],
    fields: { date: { type: 'date' } },
    relations: { act: { target: 'ato' }, players_present: { target: 'jogador', many: true },
      events: { target: 'evento', many: true }, quests: { target: 'quest', many: true },
      transcript: { target: 'transcricao', linkOnly: true } } },
  evento: { folder: 'eventos', required: ['type', 'act'],
    relations: { act: { target: 'ato' }, location: { target: 'local' },
      participants: { target: ['npc', 'jogador'], many: true }, session: { target: 'sessao' } } },
  ato: { folder: 'atos', required: ['type', 'number'],
    fields: { number: { type: 'number', required: true },
      status: { type: 'enum', values: ['upcoming', 'active', 'completed'] } },
    relations: {} },
  item: { folder: 'itens', required: ['type'],
    relations: { owner: { target: ['npc', 'jogador'] }, location: { target: 'local' } } },
  lore: { folder: 'lore', required: ['type'],
    relations: { related: { target: '*', many: true } } },
  frente: { folder: 'frentes', required: ['type'],
    fields: { status: { type: 'enum', values: ['active', 'dormant', 'resolved'] } },
    relations: { faction: { target: 'faccao' }, antagonist: { target: 'npc' },
      clocks: { target: 'relogio', many: true, curated: true }, act: { target: 'ato' } } },
  relogio: { folder: 'relogios', required: ['type', 'segments'],
    fields: { segments: { type: 'number', required: true },
      filled: { type: 'number' },
      status: { type: 'enum', values: ['ticking', 'filled', 'paused'] } },
    relations: { front: { target: 'frente' }, faction: { target: 'faccao' },
      quest: { target: 'quest' } } },
  encontro: { folder: 'encontros', required: ['type'],
    fields: { threat: { type: 'enum', values: ['trivial', 'low', 'moderate', 'severe', 'extreme'] },
      party_level: { type: 'number' }, party_size: { type: 'number' } },
    relations: { creatures: { target: 'inimigo', many: true }, location: { target: 'local' },
      session: { target: 'sessao' }, treasure: { target: 'item', many: true }, act: { target: 'ato' } } },
  desafio: { folder: 'desafios', required: ['type'],
    fields: { subsystem: { type: 'enum', values: ['influence', 'chase', 'research', 'infiltration', 'generic'] },
      vp_format: { type: 'enum', values: ['accumulating', 'diminishing', 'multiple'] },
      scale: { type: 'enum', values: ['single-check', 'quick', 'long', 'session', 'background', 'forefront'] },
      vp_target: { type: 'number' }, party_level: { type: 'number' } },
    relations: { location: { target: 'local' }, npcs: { target: 'npc', many: true },
      session: { target: 'sessao' }, act: { target: 'ato' }, faction: { target: 'faccao' },
      items: { target: 'item', many: true }, clock: { target: 'relogio' } } },
};

export const NON_ENTITY = {
  transcricao: { folder: 'sessoes/transcricoes' },
};

export const IGNORED_TOP = ['_indices', '.obsidian', '.claude', '.git'];
